"""Initial

Revision ID: c302d0f59493
Revises: 
Create Date: 2026-02-09 08:11:02.004440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c302d0f59493'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.Enum('ACTIVE', 'PAUSED', name='status_enum'), nullable=False),
    sa.Column('target_status', sa.Enum('ACTIVE', 'PAUSED', name='status_enum'), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=64, scale=2), nullable=True),
    sa.Column('spend_today', sa.Numeric(precision=64, scale=2), nullable=False),
    sa.Column('stock_days_left', sa.Integer(), nullable=True),
    sa.Column('stock_days_min', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compaigns_id'), 'compaigns', ['id'], unique=False)
    op.create_index(op.f('ix_compaigns_name'), 'compaigns', ['name'], unique=True)
    op.create_table('compaign_schedules',
    sa.Column('compaign_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compaign_id'], ['compaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compaign_schedules_compaign_id'), 'compaign_schedules', ['compaign_id'], unique=False)
    op.create_index(op.f('ix_compaign_schedules_id'), 'compaign_schedules', ['id'], unique=False)
    op.create_table('rule_evaluation_logs',
    sa.Column('compaign_id', sa.UUID(), nullable=False),
    sa.Column('triggered_rule', sa.String(length=80), nullable=True),
    sa.Column('previous_target', sa.Enum('ACTIVE', 'PAUSED', name='status_enum'), nullable=False),
    sa.Column('new_target', sa.Enum('ACTIVE', 'PAUSED', name='status_enum'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compaign_id'], ['compaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluation_logs_compaign_id'), 'rule_evaluation_logs', ['compaign_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluation_logs_id'), 'rule_evaluation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_evaluation_logs_id'), table_name='rule_evaluation_logs')
    op.drop_index(op.f('ix_rule_evaluation_logs_compaign_id'), table_name='rule_evaluation_logs')
    op.drop_table('rule_evaluation_logs')
    op.drop_index(op.f('ix_compaign_schedules_id'), table_name='compaign_schedules')
    op.drop_index(op.f('ix_compaign_schedules_compaign_id'), table_name='compaign_schedules')
    op.drop_table('compaign_schedules')
    op.drop_index(op.f('ix_compaigns_name'), table_name='compaigns')
    op.drop_index(op.f('ix_compaigns_id'), table_name='compaigns')
    op.drop_table('compaigns')
    # ### end Alembic commands ###
